[package]
name = "croupier"
version = "0.1.0"
authors = ["KwMateusz <kwidzinski.mateusz.develop@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
enum-iterator = "0.6.0"
itertools = "0.9.0"